version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.12.2
  aws-ecs: circleci/aws-ecs@1.3.0
  aws-cli: circleci/aws-cli@1.2.1

## ANCHORS
contexts: &contexts
  context: Globals

filter-masterOnly: &filter-masterOnly
  filters:
    branches:
      only: master

machine-defaults: &machine-defaults
  machine:
      image: ubuntu-2004:202101-01
      docker_layer_caching: true
      
docker-defaults: &docker-defaults
  docker:
    - image: 'cimg/python:3.8.5'

## WORKFLOW
workflows:

  build-prod:
    jobs:
      - buildEcr:
          <<: *contexts
          <<: *filter-masterOnly

jobs:
  buildEcr:
    description: Runs docker build and pushes to ecr
    parameters:
      ecrRepo:
        default: ${APP_NAME} # Set this as circleci env var
        type: string
      ecrTag:
              default: "latest"
        type: string
    <<: *machine-defaults
    steps:
      - aws-ecr/build-and-push-image:
          create-repo: true
          repo: << parameters.ecrRepo >> #hostthedocs
          aws-access-key-id: SHARED_KEY_ID
          aws-secret-access-key: SHARED_ACCESS_KEY
